### ISSUE TITLE
Only consider version tags

### ISSUE THREAD

**Issue by WalkerCodeRanger** [kzu/GitInfo#100]
I had a tag `git-info-setup` that happened to be the most recent tag in my history. Since GitInfo looks for the most recent tag, this broken the base version calculation.

Since only specific patterns are allowed for base version, the git "describe" command should be filtered to those tag patterns. Otherwise, using tags for other things breaks the version. It should be valid to use tags for more than just versions.

**Comment by kzu** [comment]
Good point! If you don't use tags for versions, you can skip their processing with `$(GitIgnoreTagVersion)`, but I guess your scenario is that you *do* use tags for versions...

**Comment by MattiasEppler** [comment]
Hi kzu 
I thing you don't have understand the problem. WalkerCodeRanger do not want to disable the versioning with tags. He want's to have tags with other things additional to version tags.

Whe have the same problem. If you create a bugfix branch with gitFlow an close the branch a tag is created with the name of the bugfix branch. Like my_super_bugfix.

The generated version is 0.0.0.commits.hash and not using the numbers of the latest version tag.

So gitInfo should only use the tags with versions and other tags should be ignored.

**Comment by DNF-SaS** [comment]
We have the same problem using gitlab (which generates own refs / tags) killing the versioning. :-(
Please make GitInfo search for a tag named a certain convention (e.g. vX.X.X) and ignore all other tags.

**Comment by kzu** [comment]
Hey folks, 
not disagreeing with the need here. I just haven't found a need for this myself, so this is quite low on my priority list. If you have the git-foo required for that, please take a look at [the target](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L674-L685) that looks it up and feel free to provide a PR. I'll gladly accept it. It's not precisely trivial doing "foreach" style processing in MSBuild, but I guess if you pull first all the tag names into an itemgroup (using `ItemName` instead of `PropertyName` for the output of the `Exec`, and then get another item filtering those by a the condition that they pass the version regex, that might work.

Thanks!
