### ISSUE TITLE
Build error when the first commit on a new branch is a cherry pick

### ISSUE THREAD

**Issue by GeRooster** [kzu/GitInfo#133]
GitInfo.2.1.2\build\GitInfo.targets(683,3): error : Could not retrieve first commit where branch xxx/yyy forked from master. Defaulting to zero commits.

**Comment by kzu** [comment]
The "error" is actually a warning, see https://github.com/kzu/GitInfo/blob/main/src/GitInfo/build/GitInfo.targets#L684. 

You most likely have configured your build to treat warnings as errors. I've now added warning codes to all warnings so you can ignore the warnings as needed.

**Comment by crypto-rsa** [comment]
We see the warning in our repository, too. We use a different branching model so the `git merge-base --fork-point` command will always fail. While it is possible to hide the GitInfo warning GI005, we also get a generic warning MSB3073 with a message `The command ... exited with code 1` which would be potentially dangerous to hide.
Do you think you could update the build targets so that this warning is not issued, or perhaps add some condition to prevent running the "fork point check" from running altogether?

**Comment by kzu** [comment]
As seen in the linked target, the entire target (that's failing for your scenario) is [conditioned with](https://github.com/devlooped/GitInfo/blob/main/src/GitInfo/build/GitInfo.targets#L671): `Condition="'$(GitBaseVersion)' == '' And '$(GitIgnoreBranchVersion)' != 'true' "`. 

So if the behavior in that target shouldn't run for you, just set `GitIgnoreBranchVersion=true` in your project file.
