### ISSUE TITLE
GitBranch is 'undefined'

### ISSUE THREAD

**Issue by SeanFeldman** [kzu/GitInfo#135]
When running using the Azure DevOps pipeline (Ubuntu 18.04.5), GitBranch is evaluated as undefined.

**Comment by kzu** [comment]
That depends on how you're checking out.

**Comment by SeanFeldman** [comment]
I don't see anything that would override the default method provided by AzDO. Could you please elaborate on what should I look at?

**Comment by kzu** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#checkout: `fetchDepth` can screw up the command used to determine the branch, [which is in the targets](https://github.com/kzu/GitInfo/blob/main/src/GitInfo/build/GitInfo.targets#L459-L469), basically `git name-rev --name-only HEAD`. 

Since DevOps already provides variables for the current branch (either `Build.SourceBranch` or `Build.SourceBranchName` depending on your needs), you can simply default `$(GitBranch)` in your `Directory.Build.props` to that:

```xml
<Project>
  <PropertyGroup>
    <GitBranch>$(BUILD_SOURCEBRANCHNAME)</GitBranch>
  <PropertyGroup>
</Project>
```

If it's empty (i.e. not building on devops), the existing behavior will populate it as usual.

**Comment by kzu** [comment]
BTW, the reason something like this isn't built-in is that every other CI system has its own variables with their own formats and default values. Since it's typically quite easy to lookup the docs on what those are and default them via .props, it's left out of GitInfo itself which just deals with calculating values that haven't been set/calculated already.

Another example is the `GitCommit`, you could default it to the devops `Build.SourceVersion` variable, for example.

**Comment by SeanFeldman** [comment]
I've learned quite a few things from this issue alone.
Thank you so much, @kzu. 🙏
