### ISSUE TITLE
The target "GitVersion" does not exist in the project

### ISSUE THREAD

**Issue by Noggog** [kzu/GitInfo#137]
This seems to be related to the comment made here: https://github.com/kzu/GitInfo/issues/62#issuecomment-367831998

I'll preface this by giving a bit of flavor.  My first introduction to GitInfo was cloning another repository that was making use of the library pretty lightly.  The solution had it imported, and printed the git sha to logs, etc.  As a new user coming in, though, I immediately ran into an error similar to the title above (may not have been exact).  After some extreme frustration at repeatedly trying to build a solution everyone else said built for them, I eventually solved my problem by uninstalling the GitInfo nuget, building, then reinstalling it.

Similarly, in my test project I made for this issue: #134 , I'm able to get a similar error _on occasion_ by some combination of cleaning, deleting obj/bin folders.  Doesn't happen 100% of the time, but after some repeated cleaning it usually does.  Once the error kicks in, though, I'm unable to build until I comment out the target, build, then comment it back in.

My solution of temporarily removing the nuget or build target seems like a very hacky non-sustainable workaround.

I feel like this is a sticky problem for two reasons:
- It turns off new forkees that run into it and don't care to diagnose what's going on
- Can this happen while building during CI?  It hasn't from my tests so far, but I don't know why it couldn't from my experience with the issue.

Do others experience this issue?  Can it somehow be avoided?... as while it's not truly gamebreaking, it does act as a major initial stumbling block in some circumstances.

**Comment by kzu** [comment]
This is typically due to one of your targets declaring a dependency on `GitVersion` from (say) a `Directory.Build.targets`. Before the nuget restore happens, indeed, that target doesn't exist, so nothing can depend on it.

The solution is to simply declare the target in your `Directory.Build.props`, and the GitInfo targets will redefine it once restore is performed. For completeness:

```
<Project>
  <!-- To be redefined by GitInfo after restore. -->
  <Target Name="GitVersion" />
</Project>
```

This trick applies to any such targets you might depend on that are coming from nuget packages, btw.

**Comment by Noggog** [comment]
You're a saint
