### ISSUE TITLE
Tag prefix per project possible ?

### ISSUE THREAD

**Issue by KorsG** [kzu/GitInfo#5]
I have a git repository with multiple VS projects that should change version independently.
Would it be possible to configure GitInfo to use tags with a certain prefix per project ?

Example: 

+ root
    + ProjectA\ProjectA.csproj
       Should use git tags with prefix a- (like a-1.1.0)

    + ProjectB\ProjectB.csproj
       Should use git tags with prefix b- (like b-1.2.0)

**Comment by kzu** [comment]
It's actually much simpler. You can just have a GitInfo.txt file inside the folder of each project, and GitInfo will automatically use the "closest" one to the project being built to determine the base version. 

The commit I just added also makes it so that the commit count will also be scoped to that directory.

**Comment by KorsG** [comment]
Thanks - just what I needed :-)

**Comment by kzu** [comment]
Closing then :+1:
