### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by drewnoakes** [kzu/GitInfo#83]
http://www.cazzulino.com/GitInfo/

Click "single .targets file".

Looks like it should be an absolute URL.

There may be others.

**Comment by Sorashi** [comment]
The link is
`https://github.com/kzu/GitInfo/blob/master/src/build/GitInfo.targets`
but should be
`https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets`

This was introduced in 482e1cfe5df72b5e92cbaecd8aa36d09539aa8b7 due to the folder structue change (the vsix folder was added and `src` was moved to `src/GitInfo`).

**Comment by Sorashi** [comment]
Interestingly enough, this had been fixed in #16, but the changes were never reflected [live](http://www.cazzulino.com/GitInfo/).

**Comment by sorashi** [comment]
To be clear - it was fixed in #16,  but then reintroduced in 662208ee786428d6bcf6529910cda7619c1fd4a0 (migration to Jekyll).

**Comment by kzu** [comment]
Fixed with the merged PR. Thanks!
