### ISSUE TITLE
Filter out remotes part in branch name

### ISSUE THREAD

**Issue by aquamoth** [kzu/GitInfo#95]
We build our application with Azure Pipelines. 
Since the pipeline checks out a specific headless commit, the resulting version becomes something like `2.1.20-remotes/origin/master+3f257bebb`. 

I want gitinfo to ignore the part of the remote, so the name becomes just `2.1.20-master+3f257bebb`.

This issue may be opposite of issue 27 though.

**Comment by kzu** [comment]
The way I typically use this with AzDO is to override `GitBranch` directly:

```
  <PropertyGroup>
    <GitBranch Condition="'$(SYSTEM_PULLREQUEST_TARGETBRANCH)' != ''">$(SYSTEM_PULLREQUEST_TARGETBRANCH)</GitBranch>
    <GitBranch Condition="'$(SYSTEM_PULLREQUEST_TARGETBRANCH)' == '' and '$(BUILD_SOURCEBRANCHNAME)' != ''">$(BUILD_SOURCEBRANCHNAME)</GitBranch>
  </PropertyGroup>
```

You can put that in a `Directory.Build.props`. I'm considering having CI-specific target includes that do this automatically (i.e. `GitInfo.AzDO.targets` imported from `GitInfo.targets` when appropriate). 

Another common strategy is changing the branch name if it's a PR (since in that case you're not likely very interested in what the source branch name is):

```
 <GitBranch Condition="'$(SYSTEM_PULLREQUEST_PULLREQUESTNUMBER)' != ''">pr$(SYSTEM_PULLREQUEST_PULLREQUESTNUMBER)</GitBranch>
```

**Comment by aquamoth** [comment]
Thanks, that was a great way of solving my needs. Thanks!
