### ISSUE TITLE
Disable gitinfo.cache

### ISSUE THREAD

**Issue by JackZylkin** [kzu/GitInfo#96]
Is there a way to disable the gitinfo.cache from being generated?  Or, to clean it out every time I make a build?  I find that the isDirty flag is often incorrect, and clearing the cache fixes this.

**Comment by JackZylkin** [comment]
Actually, I am finding that clearing the cache file does not fix the problem.  Still not sure why isDirty is often false even after making changes in my workspace.

I am on GitInfo 2.0.1

**Comment by MattiasEppler** [comment]
Im using Version 2.0.20
IsDirty is always true. I have no local changes. Everything is commited. No working tree changes.
Clean all. Deleating obj and bin folder. Nothing works. IsDirty is always true.

**Comment by MattiasEppler** [comment]
Hm.... 
If i build debug version "IsDirty" is true
If i build release version "IsDirty" is false? 
Why. Is dirty has nothing to do with debug or release?

**Comment by patrickwildenborg** [comment]
I'm using version 2.0.20
I ran into the same issue that "IsDirty" was not properly updated.

The problem doesn't seem to be the cache files, but the conditions for generating a new **ThisAssembly.GitInfo.g.cs**

The target "_GitGenerateThisAssembly", will only generate a new **ThisAssembly.GitInfo.g.cs** if "@(_GitInput)" has changed since the last time it was generated. But this  only contains the status files from the .git folder. But being dirty/clean doesn't depend only on those files, but also on all the files in your workingtree.

To fix it quick and dirty, i removed the "inputs" and "outputs" attributes from the "_GitGenerateThisAssembly" target. so that it will write a fresh **ThisAssembly.GitInfo.g.cs** during every build.

@MattiasEppler: the obj\debug and obj\release folder contain their own (possible outdated) copy of the **ThisAssembly.GitInfo.g.cs**, so they might give different results.

**Comment by kzu** [comment]
You can use [SkipGitCache](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L49) to disable the caching.

**Comment by kzu** [comment]
TBH, I never understood much the usefulness of the `IsDirty` property at all...

**Comment by MattiasEppler** [comment]
> TBH, I never understood much the usefulness of the IsDirty property at all...

Ok? For us its very important. You can see that your last assembly is not build on "clear" checked in repository. If you deliver such a assembly you have no reference to the full qualified source.

So its important I do not deliver such a version witch is marked as dirty.

**Comment by Jehoel** [comment]
I'm using GitInfo in a web-application project and VS always deletes and rebuilds my TypeScript files - at the precise moment when my project is built by VS, it deletes the output `*.js` files and this puts my repo into a dirty state (because those `*.js` files are added to git). VS doesn't rebuild my `*.js` files until after my project's output assembly DLL is generated - so `IsDirty` is always true.

Is there a good solution or workaround for this that doesn't involve excluding my `*.js` files from git via `.gitignore`? Can we instruct GitInfo to apply a filter or custom command-line arguments to use with `git` when it gets the is-dirty state?

**Comment by kzu** [comment]
How is that weird build issue affecting gitinfo? It's not clear to me. The IsDirty property is pretty much useless for me (since you should *never* ship assemblies built on anyone's personal machine, only on CI, where it's never dirty).

**Comment by MattiasEppler** [comment]
Hi kzu. Not everyone has a build server. Or like us that whe have to create builds and test the version on testmachines bevor whe can push it on the server. So its necessary that we build assemblys on our personal machines. And whe should see if its a dirty build or not.

**Comment by kzu** [comment]
Yes, everyone has a build server (or can have, anyway). It's free and every
platform for source code has one (GitHub, gitlab, DevOps, then travisci,
appveyor and so many more).

Knowing whether a package was built from a dirty repo or not doesn't add
value IMHO. You can always detect local/dev builds by checking for non-CI
instead (trivially via MSBuild props, like
https://github.com/MobileEssentials/MSBuilder/blob/master/src/CI/build/MSBuilder.CI.props)
and append a -dev label to the assembly info/package version. If you're
pushing packages anywhere from local dev boxes, you're doing it "wrong" ;-).

Anyway, there's always a million ways to do things, so, it's all good +1.

**Comment by kzu** [comment]
Since the question was on how to disable the git caching and that's readily supported, I'm closing this for now.
